### ISSUE TITLE
pip install does not install support files

### ISSUE THREAD

**Issue by fonnesbeck** [mark-hoffmann/icd#1]
When installing `icd` via pip, the `comorbidity_mappings` file does not get installed. Running both on linux and MacOS with Python 3.6 (Anaconda).

**Comment by katahdin28** [comment]
Agree - when I download via pip or directly from the pypi.org/project/icd/ pages there is no folder or file for comorbidity_mappings.  I'm running Python 3.6 / Anaconda on Win10.

**Comment by skaragou** [comment]
Also running into this issue using pip on linux.

**Comment by supatuffpinkpuff** [comment]
Having the same issue, same setup as katahdin28. Anybody know where we can get the file, or at least what manual mappings to use?

**Comment by supatuffpinkpuff** [comment]
Looks like the manual mappings can be gotten from some code at [https://web.archive.org/web/20110225031715/http://chaps.ucalgary.ca/files/chaps/ICD9_Enhanced_Elix.txt](https://web.archive.org/web/20110225031715/http://chaps.ucalgary.ca/files/chaps/ICD9_Enhanced_Elix.txt)

**Comment by mark-hoffmann** [comment]
I updated the `setup.py` with this MR https://github.com/mark-hoffmann/icd/pull/4 in order to have these downloaded and placed into the correct location on install. It should work by base install with version 0.1.3 that I just uploaded.
